### ISSUE TITLE
Unsupported style properties

### ISSUE THREAD

**Issue by astoeckley** [ckirkendall/kioo#69] opened 2015-11-09 10:15 UTC
I am trying this library to put a bunch of verbose third-party HTML content into Om components. For the most part it is working well, but some of the HTML appears to use explicit style settings and other things that perhaps kioo is not supporting:

![screen shot 2015-11-09 at 11 12 31 am](https://cloud.githubusercontent.com/assets/4611759/11031211/1bcddca8-86d3-11e5-9f78-8eac92d4b48e.png)

These errors appear when using the kioo template on this third-party HTML. Do you have advice?

**Comment by ckirkendall** [comment] 2015-11-09 12:54
This is caused by how react handles attributes.  We do some correction of
this in kioo and probably can handle these cases.  I will take a look this
week at a more comprehensive solution.

**Comment by astoeckley** [comment] 2015-11-09 13:53
Cool, thanks.

Btw this is a great library, has already saved me tremendous time.

**Comment by ckirkendall** [comment] 2016-07-03 15:36
This is fixed in master.  Sorry it took so long.

**Closed by ckirkendall** 2016-07-03 15:36 UTC
